"""Permission module constants."""

from __future__ import annotations

from app.rbac.permissions import (
    AI_CHAT,
    AI_EVALUATE,
    AI_GENERATE,
    KNOWLEDGE_CREATE,
    KNOWLEDGE_DELETE,
    KNOWLEDGE_READ,
    KNOWLEDGE_UPDATE,
    ORGANIZATION_CREATE,
    ORGANIZATION_DELETE,
    ORGANIZATION_READ,
    ORGANIZATION_UPDATE,
    PERMISSION_CREATE,
    PERMISSION_DELETE,
    PERMISSION_READ,
    PERMISSION_UPDATE,
    ROLE_ASSIGN,
    ROLE_CREATE,
    ROLE_DELETE,
    ROLE_READ,
    ROLE_UPDATE,
    TICKET_ASSIGN,
    TICKET_CLOSE,
    TICKET_CREATE,
    TICKET_DELETE,
    TICKET_READ,
    TICKET_UPDATE,
    USER_CREATE,
    USER_DELETE,
    USER_READ,
    USER_UPDATE,
    PermissionDefinition,
)

DEFAULT_PERMISSION_PAGE = 1

DEFAULT_PERMISSION_PAGE_SIZE = 20

MAX_PERMISSION_PAGE_SIZE = 100


PERMISSION_NAME_MAX_LENGTH = 100

PERMISSION_DESCRIPTION_MAX_LENGTH = 255

PERMISSION_RESOURCE_MAX_LENGTH = 100

PERMISSION_ACTION_MAX_LENGTH = 100


ALL_PERMISSION_DEFINITIONS: tuple[
    PermissionDefinition,
    ...,
] = (
    USER_CREATE,
    USER_READ,
    USER_UPDATE,
    USER_DELETE,
    ROLE_CREATE,
    ROLE_READ,
    ROLE_UPDATE,
    ROLE_DELETE,
    ROLE_ASSIGN,
    PERMISSION_CREATE,
    PERMISSION_READ,
    PERMISSION_UPDATE,
    PERMISSION_DELETE,
    ORGANIZATION_CREATE,
    ORGANIZATION_READ,
    ORGANIZATION_UPDATE,
    ORGANIZATION_DELETE,
    TICKET_CREATE,
    TICKET_READ,
    TICKET_UPDATE,
    TICKET_DELETE,
    TICKET_ASSIGN,
    TICKET_CLOSE,
    KNOWLEDGE_CREATE,
    KNOWLEDGE_READ,
    KNOWLEDGE_UPDATE,
    KNOWLEDGE_DELETE,
    AI_CHAT,
    AI_GENERATE,
    AI_EVALUATE,
)


__all__ = [
    "ALL_PERMISSION_DEFINITIONS",
    "DEFAULT_PERMISSION_PAGE",
    "DEFAULT_PERMISSION_PAGE_SIZE",
    "MAX_PERMISSION_PAGE_SIZE",
    "PERMISSION_ACTION_MAX_LENGTH",
    "PERMISSION_DESCRIPTION_MAX_LENGTH",
    "PERMISSION_NAME_MAX_LENGTH",
    "PERMISSION_RESOURCE_MAX_LENGTH",
]